export const marketData = {
  FAV: [],
  USAGUJ: [
    {
      id: 2110,
      port_name: "29",
      vessel_name: "6900 NAR +/- 50 | CURRENT LOADING",
      vessel_code: "6900N/USA/6968/TC/TUNA/Jan23",
      mining_company_id: null,
      mine: null,
      orginate: "26",
      importer: "11",
      currency: "INR",
      paymentMethod: "cash",
      liftingDays: 12,
      quantity: "126713",
      quality: "6922",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2023-01-23",
      loading_date_end: "2023-01-23",
      coa: null,
      attachments: [
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/120/MV-6900-nar-usa-0-2023-01-23-11-38-12.pdf",
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/120/MV-6900-nar-usa-1-2023-01-23-11-38-12.pdf",
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/120/MV-6900-nar-usa-2-2023-01-23-11-38-12.pdf",
      ],
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "5",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: "2023-01-23",
      loading_port_id: null,
      listed_at: "2023-06-30 23:30:05",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 3239,
      is_auction: false,
      via_cs: 0,
      created_at: "2023-01-23 06:08:12",
      updated_at: "2023-06-30 18:00:05",
      status: 1,
      has_bookmarked: false,
      coal_path: null,
      find_prices: {
        last_trade_price: "11200.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 4,
        admin_user_id: 1,
        name: "USA - GUJARAT",
        is_visible: 1,
        origin: "1",
        market_code: "USAGUJ",
        created_at: "2021-10-22T13:07:56.000000Z",
        updated_at: "2021-12-02T05:56:15.000000Z",
        marketplace_log: [
          {
            id: 249,
            marketplace_id: 4,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 247,
            marketplace_id: 4,
            marketplaceable_id: 27,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 246,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 245,
            marketplace_id: 4,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 248,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 622,
            marketplace_id: 4,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "6900 NAR +/- 50 | CURRENT LOADING",
      mining_company: null,
      origin_vessel: {
        id: 26,
        iso: "USA",
        name: "United States",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/USA.png",
        phone_code: "+1",
        currency: "USD",
        emoji_unicode: null,
        status: 1,
        currency_status: 1,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 2091,
          seller_offering_id: 2110,
          vessel_name: "MV SAMJOHN SOLIDARITY",
          coal_type_id: 1,
          coal_port_id: 29,
          loading_port_id: null,
          importer_id: 11,
          quantity: 126713,
          quality: "6968",
          quality_type: "3",
          expected_date: null,
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/120/MV-6900-nar-usa-0-2023-01-23-11-38-12.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-01-23T06:08:12.000000Z",
          updated_at: "2023-06-26T05:45:22.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 29,
            port_name: "Tuna Port",
            location: "Kutch, Gujrat",
            state: "12",
            city_id: 4794,
            pincode: "370205",
            status: 1,
            created_at: "2019-05-15T13:00:00.000000Z",
            updated_at: "2019-05-15T13:00:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2197,
          seller_offering_id: 2110,
          vessel_name: "Thalassini Niki",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: null,
          importer_id: 18,
          quantity: 131757,
          quality: "6851",
          quality_type: "3",
          expected_date: "2023-04-03 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2197/MV-6900narusatuna-2197-2023-04-03-13-02-47.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-04-03T07:32:47.000000Z",
          updated_at: "2023-04-03T07:32:47.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2209,
          seller_offering_id: 2110,
          vessel_name: "MV CAPE RAY",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: null,
          importer_id: 11,
          quantity: 123516,
          quality: "6949",
          quality_type: "3",
          expected_date: "2023-04-28 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2209/MV-6900-nar-50-current-loading-2209-2023-04-28-13-16-27.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-04-28T07:46:27.000000Z",
          updated_at: "2023-04-28T07:46:27.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2267,
          seller_offering_id: 2110,
          vessel_name: "MV STARLIGHT",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: null,
          importer_id: 11,
          quantity: 50000,
          quality: "6850",
          quality_type: "3",
          expected_date: "2023-05-22 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2267/MV-6900-nar-50-current-loading-2267-2023-05-22-11-42-18.docx",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-05-22T06:12:18.000000Z",
          updated_at: "2023-05-22T06:12:18.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2288,
          seller_offering_id: 2110,
          vessel_name: "MV. FRONTIER GARLAND",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: null,
          importer_id: 11,
          quantity: 35054,
          quality: "6847",
          quality_type: "3",
          expected_date: "2023-05-27 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2288/MV-6900-nar-50-current-loading-2288-2023-05-27-18-30-50.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-05-27T13:00:50.000000Z",
          updated_at: "2023-06-01T11:30:05.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2307,
          seller_offering_id: 2110,
          vessel_name: "MV XIN BIN HAI",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: 29,
          importer_id: 11,
          quantity: 125000,
          quality: "6889",
          quality_type: "3",
          expected_date: "2023-06-08 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2307/MV-6900-nar-50-current-loading-2307-2023-06-08-17-44-36.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-06-08T12:14:36.000000Z",
          updated_at: "2023-06-08T12:14:36.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2308,
          seller_offering_id: 2110,
          vessel_name: "MV SEA PEGASUS",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: 26,
          importer_id: 11,
          quantity: 100000,
          quality: "6938",
          quality_type: "3",
          expected_date: "2023-06-08 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2308/MV-6900-nar-50-current-loading-2308-2023-06-08-17-45-52.jpeg",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-06-08T12:15:52.000000Z",
          updated_at: "2023-06-08T12:15:52.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2311,
          seller_offering_id: 2110,
          vessel_name: "IANTHE",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: null,
          importer_id: 11,
          quantity: 125550,
          quality: "6970",
          quality_type: "3",
          expected_date: "2023-06-19 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2311/MV-6900-nar-50-current-loading-2311-2023-06-19-11-49-30.jpeg",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-06-19T06:19:30.000000Z",
          updated_at: "2023-06-19T06:19:30.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2312,
          seller_offering_id: 2110,
          vessel_name: "MV LORDSHIP",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: 29,
          importer_id: 11,
          quantity: 100000,
          quality: "7004",
          quality_type: "3",
          expected_date: "2023-06-23 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2312/MV-6900-nar-50-current-loading-2312-2023-06-23-11-45-39.jpeg",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-06-23T06:15:39.000000Z",
          updated_at: "2023-06-23T06:15:40.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 2091,
        seller_offering_id: 2110,
        vessel_name: "MV SAMJOHN SOLIDARITY",
        coal_type_id: 1,
        coal_port_id: 29,
        loading_port_id: null,
        importer_id: 11,
        quantity: 126713,
        quality: "6968",
        quality_type: "3",
        expected_date: null,
        attachment:
          "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/120/MV-6900-nar-usa-0-2023-01-23-11-38-12.pdf",
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2023-01-23T06:08:12.000000Z",
        updated_at: "2023-06-26T05:45:22.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 2162,
      port_name: "29",
      vessel_name: "6750 NAR +/- 50",
      vessel_code: "MVNYM/USA/6743/TC/TUNA/Feb23",
      mining_company_id: null,
      mine: null,
      orginate: "26",
      importer: "11",
      currency: "INR",

      paymentMethod: "advance",
      liftingDays: 30,
      quantity: "128384",
      quality: "6789",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2023-02-27",
      loading_date_end: "2023-02-27",
      coa: null,
      attachments: [
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/130/MV-mv-nymphe-0-2023-02-27-10-50-11.jpeg",
      ],
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "5",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: "2023-02-27",
      loading_port_id: 975,
      listed_at: "2023-06-29 23:30:04",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 616,
      is_auction: false,
      via_cs: 0,
      created_at: "2023-02-27 05:20:11",
      updated_at: "2023-06-29 18:00:04",
      status: 1,
      has_bookmarked: false,
      coal_path: null,
      find_prices: {
        last_trade_price: "13670.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 4,
        admin_user_id: 1,
        name: "USA - GUJARAT",
        is_visible: 1,
        origin: "1",
        market_code: "USAGUJ",
        created_at: "2021-10-22T13:07:56.000000Z",
        updated_at: "2021-12-02T05:56:15.000000Z",
        marketplace_log: [
          {
            id: 249,
            marketplace_id: 4,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 247,
            marketplace_id: 4,
            marketplaceable_id: 27,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 246,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 245,
            marketplace_id: 4,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 248,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 622,
            marketplace_id: 4,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "6750 NAR +/- 50",
      mining_company: null,
      origin_vessel: {
        id: 26,
        iso: "USA",
        name: "United States",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/USA.png",
        phone_code: "+1",
        currency: "USD",
        emoji_unicode: null,
        status: 1,
        currency_status: 1,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 2147,
          seller_offering_id: 2162,
          vessel_name: "MV NYMPHE",
          coal_type_id: 1,
          coal_port_id: 29,
          loading_port_id: 975,
          importer_id: 11,
          quantity: 128384,
          quality: "6743",
          quality_type: "3",
          expected_date: null,
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/130/MV-mv-nymphe-0-2023-02-27-10-50-11.jpeg",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-02-27T05:20:12.000000Z",
          updated_at: "2023-02-27T05:20:12.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 29,
            port_name: "Tuna Port",
            location: "Kutch, Gujrat",
            state: "12",
            city_id: 4794,
            pincode: "370205",
            status: 1,
            created_at: "2019-05-15T13:00:00.000000Z",
            updated_at: "2019-05-15T13:00:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
        {
          id: 2206,
          seller_offering_id: 2162,
          vessel_name: "GCL Luxembourg",
          coal_type_id: 1,
          coal_port_id: null,
          loading_port_id: null,
          importer_id: 11,
          quantity: 77533,
          quality: "6835",
          quality_type: "3",
          expected_date: "2023-04-22 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/vessel_attributes/2206/MV-6750-nar-50-2206-2023-04-28-14-24-12.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-04-22T09:04:52.000000Z",
          updated_at: "2023-04-28T08:54:12.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: null,
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 2147,
        seller_offering_id: 2162,
        vessel_name: "MV NYMPHE",
        coal_type_id: 1,
        coal_port_id: 29,
        loading_port_id: 975,
        importer_id: 11,
        quantity: 128384,
        quality: "6743",
        quality_type: "3",
        expected_date: null,
        attachment:
          "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/130/MV-mv-nymphe-0-2023-02-27-10-50-11.jpeg",
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2023-02-27T05:20:12.000000Z",
        updated_at: "2023-02-27T05:20:12.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 2196,
      port_name: "29",
      vessel_name: "6900 NAR +/- 50 | NEXT MONTH LOADING",
      vessel_code: "6900N/USA/6900/TC/TUNA/Apr23",
      mining_company_id: null,
      mine: null,
      orginate: "26",
      importer: "11",
      currency: "INR",
      paymentMethod: "cash",
      liftingDays: 20,
      quantity: "100000",
      quality: "6900",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2023-04-03",
      loading_date_end: "2023-04-03",
      coa: null,
      attachments: [
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/143/MV-6900-nar-50-may-loading-0-2023-04-03-16-19-18.docx",
      ],
      note: null,
      incoterm_id: null,
      tick_size: "5",
      qty_tick_size: "5",
      min_order_qty: 40,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: "2023-04-03",
      loading_port_id: null,
      listed_at: "2023-06-23 23:30:02",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 74,
      is_auction: false,
      via_cs: null,
      created_at: "2023-04-03 10:49:18",
      updated_at: "2023-06-23 18:00:02",
      status: 1,
      has_bookmarked: false,
      coal_path: null,
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 4,
        admin_user_id: 1,
        name: "USA - GUJARAT",
        is_visible: 1,
        origin: "1",
        market_code: "USAGUJ",
        created_at: "2021-10-22T13:07:56.000000Z",
        updated_at: "2021-12-02T05:56:15.000000Z",
        marketplace_log: [
          {
            id: 249,
            marketplace_id: 4,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 247,
            marketplace_id: 4,
            marketplaceable_id: 27,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 246,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 245,
            marketplace_id: 4,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 248,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 622,
            marketplace_id: 4,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "6900 NAR +/- 50 | NEXT MONTH LOADING",
      mining_company: null,
      origin_vessel: {
        id: 26,
        iso: "USA",
        name: "United States",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/USA.png",
        phone_code: "+1",
        currency: "USD",
        emoji_unicode: null,
        status: 1,
        currency_status: 1,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 2198,
          seller_offering_id: 2196,
          vessel_name: "6900 NAR +/- 50 | NEXT MONTH LOADING",
          coal_type_id: 1,
          coal_port_id: 29,
          loading_port_id: null,
          importer_id: 11,
          quantity: 100000,
          quality: "6900",
          quality_type: "3",
          expected_date: "2023-06-03 00:00:00",
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/143/MV-6900-nar-50-may-loading-0-2023-04-03-16-19-18.docx",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-04-03T10:49:18.000000Z",
          updated_at: "2023-06-03T12:47:00.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 29,
            port_name: "Tuna Port",
            location: "Kutch, Gujrat",
            state: "12",
            city_id: 4794,
            pincode: "370205",
            status: 1,
            created_at: "2019-05-15T13:00:00.000000Z",
            updated_at: "2019-05-15T13:00:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 2198,
        seller_offering_id: 2196,
        vessel_name: "6900 NAR +/- 50 | NEXT MONTH LOADING",
        coal_type_id: 1,
        coal_port_id: 29,
        loading_port_id: null,
        importer_id: 11,
        quantity: 100000,
        quality: "6900",
        quality_type: "3",
        expected_date: "2023-06-03 00:00:00",
        attachment:
          "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/143/MV-6900-nar-50-may-loading-0-2023-04-03-16-19-18.docx",
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2023-04-03T10:49:18.000000Z",
        updated_at: "2023-06-03T12:47:00.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 2230,
      port_name: "26",
      vessel_name: "6200 NAR +/- 50 | CURRENT LOADING",
      vessel_code: "6200+/USA/6204/TC/KAND/Jun23",
      mining_company_id: null,
      mine: null,
      orginate: "26",
      importer: "11",
      currency: "INR",
      paymentMethod: "cash",
      liftingDays: 40,
      quantity: "100000",
      quality: "6204",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2023-06-09",
      loading_date_end: "2023-06-09",
      coa: null,
      attachments: [
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/178/MV-6200-50-0-2023-06-09-11-21-11.pdf",
      ],
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "5",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: "2023-06-09",
      loading_port_id: 26,
      listed_at: "2023-06-23 23:30:02",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 8,
      is_auction: false,
      via_cs: null,
      created_at: "2023-06-09 05:51:11",
      updated_at: "2023-06-23 18:00:02",
      status: 1,
      has_bookmarked: false,
      coal_path: null,
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 4,
        admin_user_id: 1,
        name: "USA - GUJARAT",
        is_visible: 1,
        origin: "1",
        market_code: "USAGUJ",
        created_at: "2021-10-22T13:07:56.000000Z",
        updated_at: "2021-12-02T05:56:15.000000Z",
        marketplace_log: [
          {
            id: 249,
            marketplace_id: 4,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 247,
            marketplace_id: 4,
            marketplaceable_id: 27,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 246,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 245,
            marketplace_id: 4,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 248,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 622,
            marketplace_id: 4,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "6200 NAR +/- 50 | CURRENT LOADING",
      mining_company: null,
      origin_vessel: {
        id: 26,
        iso: "USA",
        name: "United States",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/USA.png",
        phone_code: "+1",
        currency: "USD",
        emoji_unicode: null,
        status: 1,
        currency_status: 1,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 2309,
          seller_offering_id: 2230,
          vessel_name: "MV CSSC",
          coal_type_id: 1,
          coal_port_id: 26,
          loading_port_id: 26,
          importer_id: 11,
          quantity: 100000,
          quality: "6204",
          quality_type: "3",
          expected_date: null,
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/178/MV-6200-50-0-2023-06-09-11-21-11.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-06-09T05:51:11.000000Z",
          updated_at: "2023-06-09T05:51:11.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 26,
            port_name: "Kandla Port",
            location: "Kandla Port, Gujrat",
            state: "12",
            city_id: 4965,
            pincode: "370210",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 2309,
        seller_offering_id: 2230,
        vessel_name: "MV CSSC",
        coal_type_id: 1,
        coal_port_id: 26,
        loading_port_id: 26,
        importer_id: 11,
        quantity: 100000,
        quality: "6204",
        quality_type: "3",
        expected_date: null,
        attachment:
          "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/178/MV-6200-50-0-2023-06-09-11-21-11.pdf",
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2023-06-09T05:51:11.000000Z",
        updated_at: "2023-06-09T05:51:11.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 2232,
      port_name: "29",
      vessel_name: "6900 NAR +/- 50 | OCT LOADING",
      vessel_code: "6900N/USA/6900/TC/TUNA/Jun23",
      mining_company_id: null,
      mine: null,
      orginate: "26",
      importer: "11",
      currency: "INR",
      paymentMethod: "advance",
      liftingDays: 30,
      quantity: "100000",
      quality: "6900",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2023-06-24",
      loading_date_end: "2023-06-24",
      coa: null,
      attachments: [
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/143/MV-6900-nar-50-oct-loading-0-2023-06-24-14-42-29.png",
      ],
      note: null,
      incoterm_id: null,
      tick_size: "5",
      qty_tick_size: "5",
      min_order_qty: 40,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: "2023-06-24",
      loading_port_id: null,
      listed_at: null,
      type: "1",
      today_listing_count: 0,
      total_listing_count: 0,
      is_auction: false,
      via_cs: 0,
      created_at: "2023-06-24 09:12:29",
      updated_at: "2023-06-24 09:12:30",
      status: 1,
      has_bookmarked: false,
      coal_path: null,
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 4,
        admin_user_id: 1,
        name: "USA - GUJARAT",
        is_visible: 1,
        origin: "1",
        market_code: "USAGUJ",
        created_at: "2021-10-22T13:07:56.000000Z",
        updated_at: "2021-12-02T05:56:15.000000Z",
        marketplace_log: [
          {
            id: 249,
            marketplace_id: 4,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 247,
            marketplace_id: 4,
            marketplaceable_id: 27,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 246,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 245,
            marketplace_id: 4,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 248,
            marketplace_id: 4,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 622,
            marketplace_id: 4,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "6900 NAR +/- 50 | OCT LOADING",
      mining_company: null,
      origin_vessel: {
        id: 26,
        iso: "USA",
        name: "United States",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/USA.png",
        phone_code: "+1",
        currency: "USD",
        emoji_unicode: null,
        status: 1,
        currency_status: 1,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 2313,
          seller_offering_id: 2232,
          vessel_name: "6900 NAR +/- 50 | OCT LOADING",
          coal_type_id: 1,
          coal_port_id: 29,
          loading_port_id: null,
          importer_id: 11,
          quantity: 100000,
          quality: "6900",
          quality_type: "3",
          expected_date: null,
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/143/MV-6900-nar-50-oct-loading-0-2023-06-24-14-42-29.png",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-06-24T09:12:30.000000Z",
          updated_at: "2023-06-24T09:12:30.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 29,
            port_name: "Tuna Port",
            location: "Kutch, Gujrat",
            state: "12",
            city_id: 4794,
            pincode: "370205",
            status: 1,
            created_at: "2019-05-15T13:00:00.000000Z",
            updated_at: "2019-05-15T13:00:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 2313,
        seller_offering_id: 2232,
        vessel_name: "6900 NAR +/- 50 | OCT LOADING",
        coal_type_id: 1,
        coal_port_id: 29,
        loading_port_id: null,
        importer_id: 11,
        quantity: 100000,
        quality: "6900",
        quality_type: "3",
        expected_date: null,
        attachment:
          "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/143/MV-6900-nar-50-oct-loading-0-2023-06-24-14-42-29.png",
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2023-06-24T09:12:30.000000Z",
        updated_at: "2023-06-24T09:12:30.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
  ],
  WCL: [
    {
      id: 2204,
      port_name: "7",
      vessel_name: "5100 Gar indo krishnapatnam port",
      vessel_code: "5100G/IDN/5100/TC/KRIS/May23",
      mining_company_id: null,
      mine: null,
      orginate: "28",
      importer: "11",
      currency: "INR",
      quantity: "60000",
      quality: "5100",
      quality_type: 1,
      coal_type: 1,
      loading_date: "2023-05-03",
      loading_date_end: "2023-05-03",
      coa: null,
      attachments: [
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/152/MV-5100-gar-indo-krishnapatnam-port-0-2023-05-03-16-56-47.pdf",
      ],
      note: null,
      incoterm_id: null,
      tick_size: "5",
      qty_tick_size: "5",
      min_order_qty: 35,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: "2023-05-03",
      loading_port_id: 7,
      listed_at: "2023-06-09 23:30:04",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 2,
      is_auction: false,
      via_cs: 0,
      created_at: "2023-05-03 11:26:47",
      updated_at: "2023-06-09 18:00:04",
      status: 1,
      has_bookmarked: false,
      coal_path: null,
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 8,
        admin_user_id: 128,
        name: "Krishnapatnam Port",
        is_visible: 1,
        origin: "1",
        market_code: "KRISHPT",
        created_at: "2021-10-22T13:19:42.000000Z",
        updated_at: "2022-07-26T12:20:52.000000Z",
        marketplace_log: [
          {
            id: 437,
            marketplace_id: 8,
            marketplaceable_id: 25,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 436,
            marketplace_id: 8,
            marketplaceable_id: 28,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 435,
            marketplace_id: 8,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 434,
            marketplace_id: 8,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 433,
            marketplace_id: 8,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 438,
            marketplace_id: 8,
            marketplaceable_id: 31,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 439,
            marketplace_id: 8,
            marketplaceable_id: 7,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 624,
            marketplace_id: 8,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "5100 Gar indo krishnapatnam port",
      mining_company: null,
      origin_vessel: {
        id: 28,
        iso: "IDN",
        name: "Indonesia",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/Indonesia.png",
        phone_code: "+62",
        currency: "IDR",
        emoji_unicode: "U+1F1EE U+1F1E9",
        status: 1,
        currency_status: 0,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 2217,
          seller_offering_id: 2204,
          vessel_name: "5100 Gar",
          coal_type_id: 1,
          coal_port_id: 7,
          loading_port_id: 7,
          importer_id: 11,
          quantity: 60000,
          quality: "5100",
          quality_type: "1",
          expected_date: null,
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/152/MV-5100-gar-indo-krishnapatnam-port-0-2023-05-03-16-56-47.pdf",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-05-03T11:26:47.000000Z",
          updated_at: "2023-05-03T11:26:47.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 7,
            port_name: "Krishnapatnam",
            location: "Krishnapatnam Port, Andhra Pradesh",
            state: "2",
            city_id: 4956,
            pincode: "524344",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 2217,
        seller_offering_id: 2204,
        vessel_name: "5100 Gar",
        coal_type_id: 1,
        coal_port_id: 7,
        loading_port_id: 7,
        importer_id: 11,
        quantity: 60000,
        quality: "5100",
        quality_type: "1",
        expected_date: null,
        attachment:
          "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/152/MV-5100-gar-indo-krishnapatnam-port-0-2023-05-03-16-56-47.pdf",
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2023-05-03T11:26:47.000000Z",
        updated_at: "2023-05-03T11:26:47.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 1916,
      port_name: "7",
      vessel_name: "3400 GAR INDO - KPTL",
      vessel_code: "3400M/IDN/3400/GAR/TC/KRIS/Sep22",
      mining_company_id: null,
      mine: null,
      orginate: "28",
      importer: "11",
      currency: "INR",
      quantity: "50000",
      quality: "3400",
      quality_type: 1,
      coal_type: 1,
      loading_date: "2022-09-01",
      loading_date_end: null,
      coa: "MV-3400-mifa-2022-09-01-14-26-01.docx",
      attachments: null,
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "1",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: null,
      loading_port_id: null,
      listed_at: "2023-05-08 23:30:05",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 24,
      is_auction: false,
      via_cs: 0,
      created_at: "2022-09-01 08:56:01",
      updated_at: "2023-05-08 18:00:05",
      status: 1,
      has_bookmarked: false,
      coal_path:
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/coa/MV-3400-mifa-2022-09-01-14-26-01.docx",
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 8,
        admin_user_id: 128,
        name: "Krishnapatnam Port",
        is_visible: 1,
        origin: "1",
        market_code: "KRISHPT",
        created_at: "2021-10-22T13:19:42.000000Z",
        updated_at: "2022-07-26T12:20:52.000000Z",
        marketplace_log: [
          {
            id: 437,
            marketplace_id: 8,
            marketplaceable_id: 25,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 436,
            marketplace_id: 8,
            marketplaceable_id: 28,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 435,
            marketplace_id: 8,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 434,
            marketplace_id: 8,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 433,
            marketplace_id: 8,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 438,
            marketplace_id: 8,
            marketplaceable_id: 31,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 439,
            marketplace_id: 8,
            marketplaceable_id: 7,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 624,
            marketplace_id: 8,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "3400 GAR INDO - KPTL",
      mining_company: null,
      origin_vessel: {
        id: 28,
        iso: "IDN",
        name: "Indonesia",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/Indonesia.png",
        phone_code: "+62",
        currency: "IDR",
        emoji_unicode: "U+1F1EE U+1F1E9",
        status: 1,
        currency_status: 0,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 1907,
          seller_offering_id: 1916,
          vessel_name: null,
          coal_type_id: 1,
          coal_port_id: 7,
          loading_port_id: null,
          importer_id: null,
          quantity: null,
          quality: "3400",
          quality_type: null,
          expected_date: null,
          attachment: null,
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2022-09-01T08:56:01.000000Z",
          updated_at: "2022-09-01T08:56:01.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 7,
            port_name: "Krishnapatnam",
            location: "Krishnapatnam Port, Andhra Pradesh",
            state: "2",
            city_id: 4956,
            pincode: "524344",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 1907,
        seller_offering_id: 1916,
        vessel_name: null,
        coal_type_id: 1,
        coal_port_id: 7,
        loading_port_id: null,
        importer_id: null,
        quantity: null,
        quality: "3400",
        quality_type: null,
        expected_date: null,
        attachment: null,
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2022-09-01T08:56:01.000000Z",
        updated_at: "2022-09-01T08:56:01.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 1768,
      port_name: "7",
      vessel_name: "RB2 52 FC",
      vessel_code: "RB252/ZAF/5500/NAR/TC/KRIS/Jul22",
      mining_company_id: null,
      mine: null,
      orginate: "29",
      importer: "11",
      currency: "INR",
      quantity: "70000",
      quality: "5500",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2022-07-18",
      loading_date_end: null,
      coa: "MV-rb2-52-fc-2022-07-18-15-04-23.docx",
      attachments: null,
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "1",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: null,
      loading_port_id: null,
      listed_at: "2023-04-25 01:11:13",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 18,
      is_auction: false,
      via_cs: 0,
      created_at: "2022-09-18 09:34:23",
      updated_at: "2023-05-01 10:18:40",
      status: 1,
      has_bookmarked: false,
      coal_path:
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/coa/MV-rb2-52-fc-2022-07-18-15-04-23.docx",
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 8,
        admin_user_id: 128,
        name: "Krishnapatnam Port",
        is_visible: 1,
        origin: "1",
        market_code: "KRISHPT",
        created_at: "2021-10-22T13:19:42.000000Z",
        updated_at: "2022-07-26T12:20:52.000000Z",
        marketplace_log: [
          {
            id: 437,
            marketplace_id: 8,
            marketplaceable_id: 25,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 436,
            marketplace_id: 8,
            marketplaceable_id: 28,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 435,
            marketplace_id: 8,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 434,
            marketplace_id: 8,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 433,
            marketplace_id: 8,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 438,
            marketplace_id: 8,
            marketplaceable_id: 31,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 439,
            marketplace_id: 8,
            marketplaceable_id: 7,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 624,
            marketplace_id: 8,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "RB2 52 FC",
      mining_company: null,
      origin_vessel: {
        id: 29,
        iso: "ZAF",
        name: "South Africa",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/South-Africa.png",
        phone_code: "+27",
        currency: "ZAR",
        emoji_unicode: "U+1F1FF U+1F1E6",
        status: 1,
        currency_status: 0,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 1759,
          seller_offering_id: 1768,
          vessel_name: null,
          coal_type_id: 1,
          coal_port_id: 7,
          loading_port_id: null,
          importer_id: null,
          quantity: null,
          quality: "5500",
          quality_type: null,
          expected_date: null,
          attachment: null,
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2022-07-18T09:34:24.000000Z",
          updated_at: "2022-07-18T09:34:24.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 7,
            port_name: "Krishnapatnam",
            location: "Krishnapatnam Port, Andhra Pradesh",
            state: "2",
            city_id: 4956,
            pincode: "524344",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 1759,
        seller_offering_id: 1768,
        vessel_name: null,
        coal_type_id: 1,
        coal_port_id: 7,
        loading_port_id: null,
        importer_id: null,
        quantity: null,
        quality: "5500",
        quality_type: null,
        expected_date: null,
        attachment: null,
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2022-07-18T09:34:24.000000Z",
        updated_at: "2022-07-18T09:34:24.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 1834,
      port_name: "7",
      vessel_name: "4800 GAR INDO",
      vessel_code: "4800G/IDN/4800/GAR/TC/KRIS/Aug22",
      mining_company_id: null,
      mine: null,
      orginate: "28",
      importer: "11",
      currency: "INR",
      quantity: "5000",
      quality: "4800",
      quality_type: 1,
      coal_type: 1,
      loading_date: "2022-08-08",
      loading_date_end: null,
      coa: "MV-4800-gar-indo-2022-08-08-19-02-12.docx",
      attachments: null,
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "1",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: null,
      loading_port_id: null,
      listed_at: "2023-04-25 01:11:12",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 38,
      is_auction: false,
      via_cs: 0,
      created_at: "2022-08-08 13:32:12",
      updated_at: "2023-04-24 19:41:12",
      status: 1,
      has_bookmarked: false,
      coal_path:
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/coa/MV-4800-gar-indo-2022-08-08-19-02-12.docx",
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 8,
        admin_user_id: 128,
        name: "Krishnapatnam Port",
        is_visible: 1,
        origin: "1",
        market_code: "KRISHPT",
        created_at: "2021-10-22T13:19:42.000000Z",
        updated_at: "2022-07-26T12:20:52.000000Z",
        marketplace_log: [
          {
            id: 437,
            marketplace_id: 8,
            marketplaceable_id: 25,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 436,
            marketplace_id: 8,
            marketplaceable_id: 28,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 435,
            marketplace_id: 8,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 434,
            marketplace_id: 8,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 433,
            marketplace_id: 8,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 438,
            marketplace_id: 8,
            marketplaceable_id: 31,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 439,
            marketplace_id: 8,
            marketplaceable_id: 7,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 624,
            marketplace_id: 8,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "4800 GAR INDO",
      mining_company: null,
      origin_vessel: {
        id: 28,
        iso: "IDN",
        name: "Indonesia",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/Indonesia.png",
        phone_code: "+62",
        currency: "IDR",
        emoji_unicode: "U+1F1EE U+1F1E9",
        status: 1,
        currency_status: 0,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 1825,
          seller_offering_id: 1834,
          vessel_name: null,
          coal_type_id: 1,
          coal_port_id: 7,
          loading_port_id: null,
          importer_id: null,
          quantity: null,
          quality: "4800",
          quality_type: null,
          expected_date: null,
          attachment: null,
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2022-08-08T13:32:12.000000Z",
          updated_at: "2022-08-08T13:32:12.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 7,
            port_name: "Krishnapatnam",
            location: "Krishnapatnam Port, Andhra Pradesh",
            state: "2",
            city_id: 4956,
            pincode: "524344",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 1825,
        seller_offering_id: 1834,
        vessel_name: null,
        coal_type_id: 1,
        coal_port_id: 7,
        loading_port_id: null,
        importer_id: null,
        quantity: null,
        quality: "4800",
        quality_type: null,
        expected_date: null,
        attachment: null,
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2022-08-08T13:32:12.000000Z",
        updated_at: "2022-08-08T13:32:12.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 1851,
      port_name: "7",
      vessel_name: "RB3 | 48 FC +/- 1",
      vessel_code: "RB348/ZAF/4800/NAR/TC/KRIS/Aug22",
      mining_company_id: null,
      mine: null,
      orginate: "29",
      importer: "11",
      currency: "INR",
      quantity: "70000",
      quality: "4800",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2022-08-16",
      loading_date_end: null,
      coa: "MV-rb3-48fc-krishnapatnam-port-2022-08-16-12-42-54.docx",
      attachments: null,
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "1",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: null,
      loading_port_id: null,
      listed_at: "2023-04-25 01:11:12",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 25,
      is_auction: false,
      via_cs: null,
      created_at: "2022-08-16 07:12:54",
      updated_at: "2023-05-26 11:34:35",
      status: 1,
      has_bookmarked: false,
      coal_path:
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/coa/MV-rb3-48fc-krishnapatnam-port-2022-08-16-12-42-54.docx",
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 8,
        admin_user_id: 128,
        name: "Krishnapatnam Port",
        is_visible: 1,
        origin: "1",
        market_code: "KRISHPT",
        created_at: "2021-10-22T13:19:42.000000Z",
        updated_at: "2022-07-26T12:20:52.000000Z",
        marketplace_log: [
          {
            id: 437,
            marketplace_id: 8,
            marketplaceable_id: 25,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 436,
            marketplace_id: 8,
            marketplaceable_id: 28,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 435,
            marketplace_id: 8,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 434,
            marketplace_id: 8,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 433,
            marketplace_id: 8,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 438,
            marketplace_id: 8,
            marketplaceable_id: 31,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 439,
            marketplace_id: 8,
            marketplaceable_id: 7,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 624,
            marketplace_id: 8,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "RB3 | 48 FC +/- 1",
      mining_company: null,
      origin_vessel: {
        id: 29,
        iso: "ZAF",
        name: "South Africa",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/South-Africa.png",
        phone_code: "+27",
        currency: "ZAR",
        emoji_unicode: "U+1F1FF U+1F1E6",
        status: 1,
        currency_status: 0,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 1842,
          seller_offering_id: 1851,
          vessel_name: null,
          coal_type_id: 1,
          coal_port_id: 7,
          loading_port_id: null,
          importer_id: null,
          quantity: null,
          quality: "4800",
          quality_type: null,
          expected_date: null,
          attachment: null,
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2022-08-16T07:12:54.000000Z",
          updated_at: "2022-08-16T07:12:54.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 7,
            port_name: "Krishnapatnam",
            location: "Krishnapatnam Port, Andhra Pradesh",
            state: "2",
            city_id: 4956,
            pincode: "524344",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 1842,
        seller_offering_id: 1851,
        vessel_name: null,
        coal_type_id: 1,
        coal_port_id: 7,
        loading_port_id: null,
        importer_id: null,
        quantity: null,
        quality: "4800",
        quality_type: null,
        expected_date: null,
        attachment: null,
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2022-08-16T07:12:54.000000Z",
        updated_at: "2022-08-16T07:12:54.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 1917,
      port_name: "7",
      vessel_name: "4200 GAR INDO",
      vessel_code: "4200G/IDN/4200/GAR/TC/KRIS/Sep22",
      mining_company_id: null,
      mine: null,
      orginate: "28",
      importer: "11",
      currency: "INR",
      quantity: "50000",
      quality: "4200",
      quality_type: 1,
      coal_type: 1,
      loading_date: "2022-09-01",
      loading_date_end: null,
      coa: "MV-4200-gar-indo-2022-09-01-14-27-13.docx",
      attachments: null,
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "1",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: null,
      loading_port_id: null,
      listed_at: "2023-04-25 01:11:11",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 19,
      is_auction: false,
      via_cs: 0,
      created_at: "2022-09-01 08:57:13",
      updated_at: "2023-04-24 19:41:11",
      status: 1,
      has_bookmarked: false,
      coal_path:
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/coa/MV-4200-gar-indo-2022-09-01-14-27-13.docx",
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 8,
        admin_user_id: 128,
        name: "Krishnapatnam Port",
        is_visible: 1,
        origin: "1",
        market_code: "KRISHPT",
        created_at: "2021-10-22T13:19:42.000000Z",
        updated_at: "2022-07-26T12:20:52.000000Z",
        marketplace_log: [
          {
            id: 437,
            marketplace_id: 8,
            marketplaceable_id: 25,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 436,
            marketplace_id: 8,
            marketplaceable_id: 28,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 435,
            marketplace_id: 8,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 434,
            marketplace_id: 8,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 433,
            marketplace_id: 8,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 438,
            marketplace_id: 8,
            marketplaceable_id: 31,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 439,
            marketplace_id: 8,
            marketplaceable_id: 7,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 624,
            marketplace_id: 8,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "4200 GAR INDO",
      mining_company: null,
      origin_vessel: {
        id: 28,
        iso: "IDN",
        name: "Indonesia",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/Indonesia.png",
        phone_code: "+62",
        currency: "IDR",
        emoji_unicode: "U+1F1EE U+1F1E9",
        status: 1,
        currency_status: 0,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 1908,
          seller_offering_id: 1917,
          vessel_name: null,
          coal_type_id: 1,
          coal_port_id: 7,
          loading_port_id: null,
          importer_id: null,
          quantity: null,
          quality: "4200",
          quality_type: null,
          expected_date: null,
          attachment: null,
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2022-09-01T08:57:13.000000Z",
          updated_at: "2022-09-01T08:57:13.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 7,
            port_name: "Krishnapatnam",
            location: "Krishnapatnam Port, Andhra Pradesh",
            state: "2",
            city_id: 4956,
            pincode: "524344",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 1908,
        seller_offering_id: 1917,
        vessel_name: null,
        coal_type_id: 1,
        coal_port_id: 7,
        loading_port_id: null,
        importer_id: null,
        quantity: null,
        quality: "4200",
        quality_type: null,
        expected_date: null,
        attachment: null,
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2022-09-01T08:57:13.000000Z",
        updated_at: "2022-09-01T08:57:13.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
    {
      id: 2105,
      port_name: "7",
      vessel_name: "4400/NAR/43FC/AUSTRALIAN/COAL",
      vessel_code: "4400//AUS/4400/TC/KRIS/Jan23",
      mining_company_id: null,
      mine: null,
      orginate: "25",
      importer: "11",
      currency: "INR",
      quantity: "55000",
      quality: "4400",
      quality_type: 3,
      coal_type: 1,
      loading_date: "2023-01-19",
      loading_date_end: "2023-01-19",
      coa: null,
      attachments: [
        "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/133/MV-4400nar43fcaustraliancoal-0-2023-01-19-12-25-19.docx",
      ],
      note: null,
      incoterm_id: null,
      tick_size: "1",
      qty_tick_size: "5",
      min_order_qty: 30,
      price_range_min: 0.5,
      price_range_max: 2.5,
      date_of_arrival: "2023-01-19",
      loading_port_id: 1139,
      listed_at: "2023-04-25 01:11:07",
      type: "1",
      today_listing_count: 0,
      total_listing_count: 5,
      is_auction: false,
      via_cs: 0,
      created_at: "2023-01-19 06:55:19",
      updated_at: "2023-04-24 19:41:07",
      status: 1,
      has_bookmarked: false,
      coal_path: null,
      find_prices: {
        last_trade_price: "0.00",
        best_buyer_price: "0.00",
        best_buyer_currency: "INR",
        buyer_chat_data: [],
        best_seller_price: "0.00",
        best_seller_currency: "INR",
        seller_chat_data: [],
      },
      market_place: {
        id: 8,
        admin_user_id: 128,
        name: "Krishnapatnam Port",
        is_visible: 1,
        origin: "1",
        market_code: "KRISHPT",
        created_at: "2021-10-22T13:19:42.000000Z",
        updated_at: "2022-07-26T12:20:52.000000Z",
        marketplace_log: [
          {
            id: 437,
            marketplace_id: 8,
            marketplaceable_id: 25,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 436,
            marketplace_id: 8,
            marketplaceable_id: 28,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 435,
            marketplace_id: 8,
            marketplaceable_id: 26,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 434,
            marketplace_id: 8,
            marketplaceable_id: 29,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 433,
            marketplace_id: 8,
            marketplaceable_id: 1,
            marketplaceable_type: "App\\CoalType",
          },
          {
            id: 438,
            marketplace_id: 8,
            marketplaceable_id: 31,
            marketplaceable_type: "App\\Country",
          },
          {
            id: 439,
            marketplace_id: 8,
            marketplaceable_id: 7,
            marketplaceable_type: "App\\Coal_port",
          },
          {
            id: 624,
            marketplace_id: 8,
            marketplaceable_id: 1139,
            marketplaceable_type: "App\\Coal_port",
          },
        ],
      },
      contract_name: "4400/NAR/43FC/AUSTRALIAN/COAL",
      mining_company: null,
      origin_vessel: {
        id: 25,
        iso: "AUS",
        name: "Australia",
        geoname: 0,
        flag_img: "https://coalshastra.com/images/flags/Australia.png",
        phone_code: "+61",
        currency: "AUD",
        emoji_unicode: "U+1F1E6 U+1F1FA",
        status: 1,
        currency_status: 0,
        created_at: "2018-12-18T07:24:49.000000Z",
        updated_at: "2022-08-09T01:10:39.000000Z",
      },
      vessel_attributes: [
        {
          id: 2086,
          seller_offering_id: 2105,
          vessel_name: "4400/NAR/43FC/AUSTRALIAN/COAL",
          coal_type_id: 1,
          coal_port_id: 7,
          loading_port_id: 1139,
          importer_id: 11,
          quantity: 55000,
          quality: "4400",
          quality_type: "3",
          expected_date: null,
          attachment:
            "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/133/MV-4400nar43fcaustraliancoal-0-2023-01-19-12-25-19.docx",
          city_id: null,
          domestic_coal_grade_id: null,
          disabled_at: null,
          created_at: "2023-01-19T06:55:19.000000Z",
          updated_at: "2023-01-19T06:55:19.000000Z",
          deleted_at: null,
          has_bookmarked: false,
          is_disabled: false,
          port: {
            id: 7,
            port_name: "Krishnapatnam",
            location: "Krishnapatnam Port, Andhra Pradesh",
            state: "2",
            city_id: 4956,
            pincode: "524344",
            status: 1,
            created_at: "2019-05-15T00:33:00.000000Z",
            updated_at: "2019-05-15T00:33:00.000000Z",
          },
          coaltype: {
            id: 1,
            type: "Thermal Coal",
            desc: "Thermal or Steam Coal burnt for producing heat in thermal power plants, brick kilns, forging units, rolling mills etc is referred to as thermal coal. It is also known as steam coal as it is pulverized and fed to boilers to generate steam.",
            commission: 20,
            ad_credits: 1,
            image: "1471426565.jpg",
            gst: 5,
            minimum_quantity: 30,
            cess: 400,
            created_at: "2022-05-05T08:28:39.000000Z",
            updated_at: null,
          },
          city: null,
          coal_grade: null,
        },
      ],
      importers: {
        id: 11,
        name: "NA",
      },
      incoterm: null,
      vessel_attribute_oldest: {
        id: 2086,
        seller_offering_id: 2105,
        vessel_name: "4400/NAR/43FC/AUSTRALIAN/COAL",
        coal_type_id: 1,
        coal_port_id: 7,
        loading_port_id: 1139,
        importer_id: 11,
        quantity: 55000,
        quality: "4400",
        quality_type: "3",
        expected_date: null,
        attachment:
          "https://coalshastra-bucket.s3.ap-south-1.amazonaws.com/Production/docs/admin/133/MV-4400nar43fcaustraliancoal-0-2023-01-19-12-25-19.docx",
        city_id: null,
        domestic_coal_grade_id: null,
        disabled_at: null,
        created_at: "2023-01-19T06:55:19.000000Z",
        updated_at: "2023-01-19T06:55:19.000000Z",
        deleted_at: null,
        is_disabled: false,
      },
    },
  ],
  MCL: [],
  VIZAGPT: [],
  INDOGUJ: [],
  NMANGPT: [],
  USAUN: [],
  ECL: [],
  USAM: [],
  ENNKAPT: [],
};
